### ISSUE TITLE
huggingface download failed

### ISSUE THREAD

**Issue by cdhx** [HKUNLP/UnifiedSKG#10]
Hi, thanks for sharing this exciting work!

I'm having trouble downloading the model in huggingface

when I download the tokenizer of  `hkunlp/from_all_T5_base_prefix_grailqa2`, got error

`tokenizer = AutoTokenizer.from_pretrained("hkunlp/from_all_T5_base_prefix_grailqa2")`

```
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "/home2/xh/.conda/envs/skg/lib/python3.6/site-packages/transformers/models/auto/tokenization_auto.py", line 416, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home2/xh/.conda/envs/skg/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1705, in from_pretrained
    resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs
  File "/home2/xh/.conda/envs/skg/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1776, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home2/xh/.conda/envs/skg/lib/python3.6/site-packages/transformers/models/t5/tokenization_t5_fast.py", line 136, in __init__
    **kwargs,
  File "/home2/xh/.conda/envs/skg/lib/python3.6/site-packages/transformers/tokenization_utils_fast.py", line 87, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: Permission denied (os error 13)
```

Same problem happens on others like  `from_all_T5_base_prefix_compwebq2`,  but download the model of them works fine.

looking forward to your reply, thx

**Comment by ChenWu98** [comment]
Hi! Could you try `T5Tokenizer.from_pretrained("hkunlp/from_all_T5_base_prefix_grailqa2")` instead? 
Please let us know if it still does not work, and sorry for the confusion!

**Comment by cdhx** [comment]
It works, thanks for your quickly replay!

**Comment by Timothyxxx** [comment]
(Or unable the use_fast by `use_fast=False`.

**Comment by cdhx** [comment]
> 
It also work, thanks

**Comment by cdhx** [comment]
> (Or unable the use_fast by `use_fast=False`.

it also works, thanks!

**Comment by Timothyxxx** [comment]
You are welcome, you can check [colab](https://colab.research.google.com/drive/1f9yTXC3GpSyRJOjzsKceG_bhk-Cw71Ga#scrollTo=-tikpsWEr-Fk) demo for examples of usage or contact us!😃

**Comment by cdhx** [comment]
I run the demo on colab, got this error, I have install the environment in yaml file

```
import datasets
from transformers import (
    HfArgumentParser,
    set_seed,
    AutoTokenizer
)
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "/home2/xh/.conda/envs/skg/lib/python3.7/site-packages/transformers/file_utils.py", line 1985, in __getattr__
    value = getattr(module, name)
  File "/home2/xh/.conda/envs/skg/lib/python3.7/site-packages/transformers/file_utils.py", line 1984, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home2/xh/.conda/envs/skg/lib/python3.7/site-packages/transformers/file_utils.py", line 1993, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home2/xh/.conda/envs/skg/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home2/xh/.conda/envs/skg/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 22, in <module>
    from ... import GPTNeoConfig
  File "/home2/xh/.conda/envs/skg/lib/python3.7/site-packages/transformers/file_utils.py", line 1985, in __getattr__
    value = getattr(module, name)
  File "/home2/xh/.conda/envs/skg/lib/python3.7/site-packages/transformers/file_utils.py", line 1984, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home2/xh/.conda/envs/skg/lib/python3.7/site-packages/transformers/file_utils.py", line 1993, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home2/xh/.conda/envs/skg/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home2/xh/.conda/envs/skg/lib/python3.7/site-packages/transformers/models/gpt_neo/configuration_gpt_neo.py", line 22, in <module>
    from ...onnx import OnnxConfigWithPast, PatchingSpec
  File "/home2/xh/.conda/envs/skg/lib/python3.7/site-packages/transformers/onnx/__init__.py", line 17, in <module>
    from .convert import export, validate_model_outputs
  File "/home2/xh/.conda/envs/skg/lib/python3.7/site-packages/transformers/onnx/convert.py", line 23, in <module>
    from .. import PreTrainedModel, PreTrainedTokenizer, TensorType, TFPreTrainedModel, is_torch_available
ImportError: cannot import name 'TFPreTrainedModel' from 'transformers' (/home2/xh/.conda/envs/skg/lib/python3.7/site-packages/transformers/__init__.py)
```
